### ISSUE TITLE
AQuery OutOfMemoryError

### ISSUE THREAD

**Issue by antest1** [antest1/kcanotify#17]
### Stack Trace
java.lang.OutOfMemoryError: pthread_create (stack size 16384 bytes) failed: Try again
at java.lang.VMThread.create(Native Method)
at java.lang.Thread.start(Thread.java:1029)
at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1327)
at com.a.b.a.execute(AbstractAjaxCallback.java:1311)
at com.a.b.a.work(AbstractAjaxCallback.java:962)
at com.a.b.a.async(AbstractAjaxCallback.java:921)
at com.a.b.a(AbstractAQuery.java:2868)
at com.antest1.kcanotify.KcaService.handleServiceMessage(KcaService.java:1318)
at com.antest1.kcanotify.KcaService$kcaServiceHandler.handleMessage(KcaService.java:424)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5336)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:873)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
at dalvik.system.NativeStart.main(Native Method)

**Comment by antest1** [comment]
Since AQuery library is not used anymore, close this issue.
