### ISSUE TITLE
2.4.6 Bugs

### ISSUE THREAD

**Issue by antest1** [antest1/kcanotify#31]
Please report the bug if there was a problem with some kcanotify functions.
About sniffer(VPN) issue, please read #30.

- Event map information will be updated after gathering some information.

**Comment by antest1** [comment]
Quest Track Bug: counter does not count up for some quest in 80% status.

**Comment by antest1** [comment]
USER_COMMENT=
ANDROID_VERSION=7.0
APP_VERSION_NAME=2.4.6
BRAND=htc

CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to resume activity {com.antest1.kcanotify/com.antest1.kcanotify.KcaInspectorDetailActivity}: java.lang.IllegalArgumentException
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3625)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3665)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1551)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:173)
at android.app.ActivityThread.main(ActivityThread.java:6459)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
Caused by: java.lang.IllegalArgumentException
at android.os.Parcel.readException(Parcel.java:1696)
at android.os.Parcel.readException(Parcel.java:1645)
at android.app.ActivityManagerProxy.isTopOfTask(ActivityManagerNative.java:5556)
at android.app.Activity.isTopOfTask(Activity.java:5970)
at android.app.Activity.onResume(Activity.java:1257)
at android.support.v4.a.t.onResume(FragmentActivity.java:446)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1337)
at android.app.Activity.performResume(Activity.java:6777)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3596)
... 8 more
java.lang.IllegalArgumentException
at android.os.Parcel.readException(Parcel.java:1696)
at android.os.Parcel.readException(Parcel.java:1645)
at android.app.ActivityManagerProxy.isTopOfTask(ActivityManagerNative.java:5556)
at android.app.Activity.isTopOfTask(Activity.java:5970)
at android.app.Activity.onResume(Activity.java:1257)
at android.support.v4.a.t.onResume(FragmentActivity.java:446)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1337)
at android.app.Activity.performResume(Activity.java:6777)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3596)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3665)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1551)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:173)
at android.app.ActivityThread.main(ActivityThread.java:6459)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)

**Comment by antest1** [comment]
All above bugs are fixed in 2.4.6 rev1.
Close the issue.
