### ISSUE TITLE
Error In BattleView

### ISSUE THREAD

**Issue by antest1** [antest1/kcanotify#4]
- **java.lang.IndexOutOfBoundsException Invalid index (friend fleet)**
  - at com.antest1.kcanotify.KcaBattleViewService.setItemViewLayout(KcaBattleViewService.java:880) 
- **java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.widget.ScrollView.findViewById(int)' on a null object reference**
  - at com.antest1.kcanotify.KcaBattleViewService.setViewLayout(KcaBattleViewService.java:840)

**Comment by antest1** [comment]
since there are no problem with recent version(2.1.3), so close the issue.
