### ISSUE TITLE
OutOfMemoryError in KcaHandler string processing

### ISSUE THREAD

**Issue by antest1** [antest1/kcanotify#5]
Occurs in old phones (Like Galaxy Note II)

Error Log:
CUSTOM_DATA=
APP_VERSION_NAME=2.1.3r4
BRAND=samsung
USER_COMMENT=null
STACK_TRACE=java.lang.OutOfMemoryError
at java.lang.String.<init>(String.java:255)
at java.lang.String.<init>(String.java:171)
at java.lang.String.<init>(String.java:141)
at com.antest1.kcanotify.KcaHandler.run(KcaHandler.java:66)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)

**Comment by antest1** [comment]
Fixed in 7ef4db4.
